module.exports = {
    util: require('./Functions/utility'),
    alliance: require('./Functions/alliances'),
    character: require('./Functions/character'),
    contracts: require('./Functions/contracts'),
    corporation: require('./Functions/corporation'),
    dogma: require('./Functions/dogma'),
    fw: require('./Functions/factionWarfare'),
    incursions: require('./Functions/incursions'),
    industry: require('./Functions/industry'),
    insurance: require('./Functions/insurance'),
    killmails: require('./Functions/killmails'),
    loyalty: require('./Functions/loyalty'),
    market: require('./Functions/market'),
    opportunities: require('./Functions/opportunities'),
    pi: require('./Functions/planetaryInteraction'),
    routes: require('./Functions/routes'),
    search: require('./Functions/search'),
    sov: require('./Functions/sovereignty'),
    status: require('./Functions/status'),
    universe: require('./Functions/universe'),
    wars: require('./Functions/wars')
}
